# the below script is a revised version of "iskay2_extract_ap_photo.py"
# call is sbatch ap_photo.sh 
from iskay2 import paramfile
from iskay2 import maptools
from iskay2 import rcfile
from iskay2 import catalogtools
from iskay2 import ap_photo
import pandas as pd
import os, sys
import numpy as np

map_dir = '/hpc/group/cosmology/jem189/scratch/data/maps'
cat_dir = '/work/jem189/scratch/data/catalogs'

def save_ap_photo(df_res, outpath):
    if not os.path.exists(results_folder):
        os.mkdir(results_folder)
    df_res.to_hdf(os.path.join(results_folder, outpath),
                  key='df_ap_photo',
                  mode='w')
    print(f'saved results to {os.path.join(results_folder, outpath)}')

# load param and rc files
params = paramfile.load_paramfile()
rc = rcfile.load_rcfile()
newparams = paramfile.load_paramfile(sys.argv[1])
# params.json is the default paramfile generated by iskay2
# many of the params are not relevant to the tSZ analysis
# here we redefine the parameters needed for tSZ AP
print('overriding default params...')
params['MAP_FNAME'] = os.path.join(map_dir, newparams['map_name'])+'.fits'
params['DIVMAP_FNAME'] = os.path.join(map_dir, 'act_planck_s08_s22_f150_night_ivar.fits') # not used in analysis but required for iskay2 code
params['CAT_FNAME'] = os.path.join(cat_dir, newparams['cat_name'])+'.csv' 
params['R_DISKS_ARCMIN'] = np.arange(newparams['min_r'], newparams['max_r'], 0.5)

# print the redefined params to the output file 
print('NEW PARAMS')
for element in params:
    print("%s: %s" % (element, params[element]))

# load map and catalog
themap = maptools.load_map(params, rc=rc)
the_noise_map = maptools.load_map(params,
                                  rc=rc,
                                  noisemap=True)
df = catalogtools.load_catalog(params, rc=rc)

# use small chunk of catalog if testing script
isTest = sys.argv[2]
if isTest == 'True':
    df = df.head(100)

# perform the aperture photometry
df_ap_photo = ap_photo.get_ap_photo_in_catalog(df,
                                               themap,
                                               the_noise_map,
                                               params, rc)

# save the results
mapname = newparams['map_name'] 
catname = newparams['cat_name'] 
if isTest == 'True':
    outpath = f'{catname}_{mapname}_test.hdf'
else:
    outpath = f'{catname}_{mapname}.hdf'
outdir = '/work/jem189/scratch/data/ApPhotoResults'
results_folder = os.path.join(outdir, catname)                          
print(f'results will be saved to {results_folder}')
save_ap_photo(df_ap_photo, outpath)
